title: 孤独の観测者
# description: 0.571024<br>0.571015<br>0.523299<br>0.456903<br>0.409420<br>0.337187<br>0.334581<br>0.337337<br>0.337199<br>0.328403<br>......<br>1.048596<br>
description: <br><strong>1. Be Impeccable With Your Word</strong><br>Speak with integrity. Say only what you mean. Avoid using the word to speak against yourself or to gossip about others. Use the power of your word in the direction of truth and love. <br><br><strong>2. Don’t Take Anything Personally</strong><br>Nothing others do is because of you. What others say and do is a projection of their own reality, their own dream. When you are immune to the opinions and actions of others, you won’t be the victim of needless suffering. <br><br><strong>3. Don’t Make Assumptions</strong><br>Find the courage to ask questions and to express what you really want. Communicate with others as clearly as you can to avoid misunderstandings, sadness and drama. With just this one agreement, you can completely transform your life.<br><br><strong>4. Always Do Your Best</strong><br>Your best is going to change from moment to moment; it will be different when you are healthy as opposed to sick. Under any circumstance, simply do your best, and you will avoid self-judgment, self-abuse, and regret.
theme: jekyll-theme-minimal
repository: sbwkl/sbwkl.github.io
google_analytics: UA-92300152-2
markdown: kramdown

github:
    is_project_page: false
    is_user_page: false
    owner_name: 観测者
    
plugins: [jekyll-mermaid]
port: 4005